from pathlib import Path
import json,html
R=Path(__file__).resolve().parents[1];stats=json.loads((R/'data/brand-stats.json').read_text());e=html.escape
BOOK='https://one.onegame.tw/';LINE='https://lin.ee/fhLAwUE'
nav=[('/find/','找門市'),('/how-it-works/','怎麼玩'),('/spaces/','空間體驗'),('/app/','ONE APP'),('/franchise/','加盟 ONE'),('/about/','品牌故事')]
def link(url,text,cl='text-link'):return f'<a class="{cl}" href="{url}">{text}</a>'
def section(body,cl='',id=''):return f'<section class="section {cl}"'+(f' id="{id}"' if id else '')+f'><div class="wrap">{body}</div></section>'
def shot(name,alt,cl=''):
 return f'<button class="actual-shot {cl}" data-image="/assets/{name}" data-caption="{alt}" aria-label="放大{alt}"><img src="/assets/{name}" alt="{alt}" loading="lazy"><span>實際產品畫面 <b>放大查看 ↗</b></span></button>'
def photo(name,alt,cl=''):return f'<figure class="photo {cl}"><img src="/images/{name}.jpg" alt="{alt}" loading="lazy"><figcaption>{alt}</figcaption></figure>'
def intro(title,desc,tag=''):return section(f'<div class="page-intro">'+(f'<p class="eyebrow">{tag}</p>' if tag else '')+f'<h1>{title}</h1><p>{desc}</p></div>','intro')
def proof():return section(f'<div class="proof"><div><strong>{stats["storesDisplay"]}</strong><span>全台品牌門市</span></div><div><strong>{stats["members"]:,}</strong><span>品牌累積會員</span></div><div><strong>{stats["founded"]}</strong><span>第一間 ONE 開始</span></div></div><p class="caption">更新 {stats["updatedAt"]} · {stats["note"]}</p>','proof-section')
def finder():return f'''<div class="finder" data-finder><form class="finder-controls"><label>選擇縣市<select name="city"><option value="">全台門市</option></select></label><label>搜尋門市或地址<input name="search" type="search" placeholder="例如：西屯、一中" autocomplete="off"></label><button type="button" class="button secondary" data-nearby>找附近門市</button></form><p class="caption" data-directory-date>正在讀取門市資料…</p><p role="status" data-result-status></p><div class="store-list" data-stores></div><button class="button secondary" data-more type="button" hidden>顯示更多門市</button><noscript><p>請開啟 JavaScript 使用門市篩選，或直接進入 ONE 預約系統。</p></noscript><p class="finder-note">門市照片、價格與最新空檔，請在各店預約頁查看。官網不顯示未確認的即時空位。</p>{link(BOOK,'開啟 ONE 全台門市 ↗')}</div>'''
def steps():return '<ol class="steps">'+''.join(f'<li><span>0{i}</span><h3>{a}</h3><p>{b}</p></li>' for i,(a,b) in enumerate([('找門市','選一間方便集合的 ONE。'),('選座位／包廂','查看照片、設備與空檔。'),('APP 預約付款','先看清楚時段與費用。'),('到店開始','依訂單及門市指引使用。')],1))+'</ol>'
def gallery():
 items=json.loads((R/'data/space-photos.json').read_text())
 return '<div class="gallery" aria-label="ONE 實際門店相簿">'+''.join(f'<button class="gallery-item" data-image="/images/{item["name"]}.jpg" data-caption="{item["caption"]}" aria-label="放大{item["caption"]}"><img src="/images/{item["name"]}.jpg" alt="{item["caption"]}" loading="lazy"><span>{item["caption"]} ↗</span></button>' for item in items)+'</div><p class="caption">左右滑動，點照片可放大。皆為實際門市照片；設備與配置以各店現況為準。</p>'

def appstory():
 items=[('找一間喜歡的店','依地點找門市，看看店內環境。','one-stores-20261007.png'),('選好座位與時間','實際空檔與可用方案，在預約頁查看。','one-booking-20261007.png'),('確認費用，再付款','確認門市、日期、時段與付款金額。','one-checkout-20261007.png')]
 return '<div class="app-story" data-story><div class="story-copy"><h2>下一次相聚，<br>用 ONE 安排。</h2><div role="tablist" aria-label="ONE APP 操作">'+''.join(f'<button role="tab" id="app-tab-{i}" aria-controls="app-panel-{i}" aria-selected="{str(i==0).lower()}" tabindex="{0 if i==0 else -1}" data-story-tab="{i}"><span>0{i+1}</span><div><h3>{a}</h3><p>{b}</p></div></button>' for i,(a,b,c) in enumerate(items))+'</div>'+link(BOOK,'開啟 ONE，查看座位','button')+'</div><div class="story-visual">'+''.join(f'<div role="tabpanel" id="app-panel-{i}" aria-labelledby="app-tab-{i}" {"hidden" if i else ""}>'+shot(c,a)+'</div>' for i,(a,b,c) in enumerate(items))+'</div></div>'
scenarios=[('今天晚上還有位置嗎？','先選門市與日期','最新空檔會隨訂單變動，請開啟門市預約頁查看；需要協助時可聯絡客服。','/find/','查門市空檔'),('這間店怎麼計費？','先看方案，再付款','各店依座位、日期及時段提供方案，預約前會顯示應付金額。','/find/','查各店價格'),('麻將桌沒反應怎麼辦？','先確認訂單是否開始','確認訂單時段與現場電源指示；請勿拆機或自行維修，交由客服協助判斷。',LINE,'聯絡客服'),('可以延長時間嗎？','先查看後續是否可預約','開啟目前訂單查看加時入口；是否能續時及費用，以系統顯示為準。',BOOK,'開啟我的訂單')]
def support():return '<div class="support-demo" data-support><div><h2>有問題，<br>直接問。</h2><p>先找答案，需要協助再接上客服。</p><div class="question-buttons" role="tablist" aria-label="常見客服情境">'+''.join(f'<button role="tab" id="question-{i}" aria-controls="answer-{i}" aria-selected="{str(i==0).lower()}" tabindex="{0 if i==0 else -1}" data-question="{i}">{a}</button>' for i,(a,b,c,d,f) in enumerate(scenarios))+'</div></div><div class="support-answer">'+''.join(f'<div role="tabpanel" id="answer-{i}" aria-labelledby="question-{i}" {"hidden" if i else ""}><span class="eyebrow">常見問題指引</span><h3>{b}</h3><p>{c}</p>{link(d,f,"button secondary")}</div>' for i,(a,b,c,d,f) in enumerate(scenarios))+'<p class="caption">這是操作指引，不是即時 AI 對話。AI 查位、電話與轉接服務依門市開通情況提供。</p><div class="actions">'+link(LINE,'LINE 詢問','button')+link('tel:0970199296','打電話詢問','button secondary')+'</div></div></div>'
def system():return '<div class="system-story"><div class="system-copy"><p class="eyebrow">ONE 營運系統</p><h2>顧客用得順，<br>店家看得清。</h2><p>從預約到現場，讓同一筆訂單接好每一步。</p><ol class="flow"><li>顧客預約</li><li>線上支付、成立訂單</li><li>依訂單時段連動控電</li><li>現場自助收款</li><li>後台查看桌況與營收</li></ol>'+link('/franchise/#pricing','看方案包含什麼')+'</div><div class="system-images">'+shot('one-admin-20261007.png','ONE 店家後台・營運總覽')+'<button class="actual-shot kiosk-photo" data-image="/images/one-guangcai-kiosk.jpg" data-caption="嘉義光彩店・現場自助繳費機" aria-label="放大現場自助繳費機照片"><img src="/images/one-guangcai-kiosk.jpg" alt="嘉義光彩店現場使用的自助繳費機" loading="lazy"><span>門市實際設備 <b>放大查看 ↗</b></span></button>'+'<p class="caption">後台為真實介面，營收不代表單店收益。繳費機攝於嘉義光彩店，支援現金與 LINE Pay；各店配置依實際設備為準。</p></div></div>'
def faq(items):return '<div class="faq">'+''.join(f'<details><summary>{q}</summary><p>{a}</p></details>' for q,a in items)+'</div>'
def finalcta():return section('<div class="closing"><h2>下一場，<br>約在 ONE。</h2><div>'+link('/find/','找附近門市','button')+link(BOOK,'立即預約','button secondary')+link('/franchise/','想開店？了解加盟 ONE')+'</div></div>','closing-section')
pricing='''<div class="pricing-head"><div><p class="eyebrow">ONE 品牌加盟方案</p><h2>從預約，到現場。</h2><p>品牌、APP、系統與基礎設備，一起規劃。</p></div><div class="price"><span>NT$</span><strong>300,000</strong><small>方案價格・新臺幣</small></div></div><div class="included"><h3>30 萬元包含</h3><ul><li>ONE APP 顧客預約，可預約 2 個月內座位</li><li>店家管理後台、品牌與會員體系</li><li>智能雲端繳費機 1 台，支援現金與 LINE Pay</li><li>智慧控電系統 10 組</li><li>場勘 1 次、格局設計圖 1 次</li><li>免費協助申請線上金流</li></ul></div><div class="fee-table"><h3>還有哪些費用？</h3><dl><div><dt>超過 10 組控電</dt><dd>超出組數另行報價，依現場桌數與配置確認。</dd></div><div><dt>裝潢、家具與其他施工</dt><dd>依場地與交付範圍另列報價；30 萬方案不代表整店所有工程全包。</dd></div><div><dt>系統月費、金流與稅額</dt><dd>固定月費、抽成、交易手續費及含稅與否，於正式報價逐項列明。</dd></div><div><dt>AI 電話、冷氣控制、電子發票</dt><dd>可依需求加購／加碼配置，開通、設備及後續費用依方案確認。</dd></div></dl></div>'''
addons='''<h2>把重複的事，<br>再少一點。</h2><div class="upgrade-rows"><article><span class="accent-red">特色加碼／AI 電話</span><h3>電話有人接，問題有人接手。</h3><p>依門市開通的資料與功能回覆空位、價格及常見設備問題，特殊狀況再轉接人員或留下紀錄。</p></article><article><span class="accent-red">特色加碼／紅外線冷氣控制</span><h3>訂單連動冷氣，後台隨時接管。</h3><p>預約開始自動開機控溫；客人調錯設定或找不到遙控器時，可從後台遠端調整。先確認冷氣機型相容性。</p></article><article><span>電子發票服務</span><h3>收款即開票，自動不漏接。</h3><p>串接電子發票服務，支援手機載具與公司統編；須完成申請及設定，費用另依方案確認。</p></article></div>'''
franchisefaq=[('加入 ONE 和自己開店差在哪？','加入 ONE 使用既有品牌、ONE APP、會員體系與營運流程。若希望保留自己的品牌，可另了解智摸；兩者合作內容不同。'),('同一區域可以開幾間 ONE？','同區最多 4 家品牌門市，採同區價格一致、禁止削價的合作規則。區域範圍、剩餘名額與執行條件以正式合作文件確認。'),('加入就有固定客源或保證回本嗎？','沒有收益或固定客源保證。品牌累積會員可增加曝光機會，實際來客與收益仍受地點、成本、經營及服務影響。'),('一條龍建置會做到哪裡？','可從場地與格局規劃、設備、系統設定到測試交接一起安排。實際工程、家具、追加設備及費用在報價逐項列明。'),('無人化是否完全不需要人？','仍須安排清潔、巡檢、設備維修與特殊客訴處理；系統協助日常預約、付款及設備管理。')]
P={}
P['/']=('ONE桌遊｜找門市、看座位、立即預約','24H 自助桌遊與麻將空間。找 ONE 門市、查看座位與價格，了解 APP 預約及加盟方案。',f'''<section class="hero"><div class="wrap hero-layout"><div class="hero-copy"><p class="eyebrow">24H 自助桌遊・麻將空間</p><h1>想玩，<br>就來。</h1><p>從找門市、選座位到預約付款，<br>用 ONE APP 就能完成。</p><div class="actions">{link('/find/','找附近門市','button')}{link(BOOK,'立即預約','button secondary')}</div>{link('/franchise/','了解加盟 ONE')}</div><div class="hero-image"><img src="/images/one-yadong-sage.jpg" alt="土城亞東店實景，麻將桌與綠色座椅" fetchpriority="high" width="1477" height="1108"><div class="hero-note">留一點時間，給相聚。</div></div></div></section>'''+section('<div class="section-head"><h2>今天想去哪一間？</h2><p>找店、看座位，再出發。</p></div>'+finder(),id='find')+section('<h2>第一次來？30 秒看懂。</h2>'+steps(),'soft')+section(appstory())+section('<h2>每間 ONE，<br>都有自己的樣子。</h2>'+gallery(),'spaces-section')+proof()+section(support())+section('<div class="franchise-invitation"><div><p class="eyebrow">想經營一間 ONE？</p><h2>不只掛上招牌，<br>一起把店開起來。</h2><p>品牌、APP、會員、系統與設備，接上已經實際運作的營運方式。</p>'+link('/franchise/','加盟 ONE・看方案與費用','button')+'</div>'+photo('one-yizhong-room','台中一中店・實際包廂')+'</div>','soft')+section('<div class="split"><div><h2>顧客用得順，<br>店家看得清。</h2><p>APP、後台、控電與自助繳費，串起門店日常。</p>'+link('/franchise/system/','看 ONE 營運系統')+'</div>'+shot('one-admin-20261007.png','ONE 店家管理後台','cropped')+'</div>')+section('<div class="story-quote"><span>2023 → 今天</span><h2>從一間店，<br>到更多人的聚會地點。</h2><p>我們從自己的門店開始，把預約、付款與自助設備，一步步做到日常裡。</p>'+link('/about/','ONE 的故事')+'</div>')+finalcta())
P['/find/']=('找門市與價格｜ONE桌遊','搜尋 ONE桌遊門市、地址與營業資訊，前往各店查詢座位、費率和即時預約。',intro('今天，想在哪裡聚？','選地點，找門市。座位、費用與預約，一起看清楚。')+section(finder())+section('<div class="split"><h2>價格先知道，<br>再決定待多久。</h2><div><p>消費價格依門市、座位、日期與使用時段而不同。選好門市及時段後，預約頁會顯示可用方案與金額。</p><p>付款前請確認計費單位、使用起訖時間及取消規則；續時費用以訂單頁為準。</p></div></div>','soft'))
P['/how-it-works/']=('第一次來怎麼玩｜ONE桌遊','找門市、選座位、APP 預約付款、到店開始。ONE桌遊第一次使用指南。',intro('第一次來，<br>這樣就可以。','先確認座位與時間，到店依訂單指引開始。')+section(steps())+section(appstory(),'soft')+section('<h2>出發前，先確認。</h2>'+faq([('需要先預約嗎？','建議先在 ONE APP 確認空檔並完成預約；部分門市可使用現場繳費機，仍以門市配置與可用座位為準。'),('現場可以付現嗎？','ONE 方案的自助繳費機支援現金與 LINE Pay，實際可用付款方式請看各門市設備與系統提示。'),('時間到了還想繼續？','請先在訂單查看續時入口與後續空檔，完成加時付款後再繼續使用；不要直接超時使用。'),('怎麼取消或退款？','請依訂單頁及門市公布的取消規則操作；付款或退款疑問請提供訂單資訊給官方客服，不要在公開留言貼個資。')]))+finalcta())
P['/app/']=('ONE APP｜找店、預約與付款','用 ONE APP 找門市、查看座位與使用方案，預約付款、查看訂單與續時。',intro('相聚的事，<br>在手機上安排。','找店、看座位、預約與付款，用熟悉的 ONE APP。')+section(appstory())+section('<div class="split"><h2>價格、時間，<br>預約前先看清楚。</h2><div><p>可預約 2 個月內座位。依各店開放時段、方案與實際空檔選擇，付款後回到訂單查看使用資訊。</p><p>會員帳號可使用 ONE 品牌門市；儲值餘額、票券與優惠的適用範圍，依各店規則與票券說明。</p>'+link(BOOK,'開啟 ONE 預約系統','button')+'</div></div>','soft'))
P['/spaces/']=('空間體驗｜ONE桌遊','看看 ONE桌遊真實門店、麻將包廂與聚會空間。設備與配置依各門市為準。',intro('每間 ONE，<br>都有自己的樣子。','找一個喜歡的空間，留給朋友和自己。')+section(gallery())+section('<div class="split"><h2>選空間，<br>也選聚會的方式。</h2><div><p>看照片、確認人數，再選適合的座位或包廂。部分門市提供沙發、電視或影音設備，請先查看該店介紹。</p>'+link('/find/','找一間喜歡的 ONE','button')+'</div></div>')+finalcta())
P['/support/']=('客服與常見問題｜ONE桌遊','ONE 預約、價格、續時與设备問題，查閱指引或聯絡官方 LINE、電話客服。',intro('有問題，直接問。','查門市、看價格、預約或設備問題，找到正確的協助入口。')+section(support())+section('<div class="split"><h2>需要人協助？</h2><div><p>聯絡時提供門市名稱與訂單資訊，讓客服更快了解狀況。若有焦味、冒煙或電線異常，請停止使用並通知門市。</p><div class="actions">'+link(LINE,'LINE 詢問','button')+link('tel:0970199296','撥打 ONE 客服','button secondary')+'</div><p class="caption">ONE 客服 0970-199296。電話是否由 AI 接聽、轉接及服務時段，依實際開通與客服安排。</p></div></div>','soft'))
P['/franchise/']=('加盟 ONE｜30 萬方案、設備與開店支援','了解 ONE桌遊品牌加盟 300,000 元方案，含 10 組控電與 1 台繳費機、區域保障及加購費用。',intro('想經營一間 ONE？','接上品牌、ONE APP 與會員體系，從規劃到開店一起準備。','ONE 品牌加盟')+proof()+section('<div class="split"><h2>加入的，<br>是一套營運方式。</h2><div><p>顧客用 ONE APP，店家用同一套後台管理訂單、桌況與營收；現場串接控電、自助繳費與支付。</p><p>品牌營運支援、開店規劃、操作交接及後續系統服務，依合作內容安排。</p>'+link('/franchise/system/','看真實 APP、後台與設備')+'</div></div>')+section(pricing,'pricing-section','pricing')+section(addons,id='addons')+section('<div class="split"><h2>區域保障，<br>價格一起維護。</h2><div><p class="large-copy">同區最多 4 家店。<br>同區價格一致，禁止削價。</p><p>申請前先確認區域與名額；實際區域劃分、費率及合作規則以正式文件為準。</p>'+link('https://ken0900101318-beep.github.io/one-store-quota/','查看區域名額 ↗')+'</div></div>','soft','territory')+section('<h2>從場地，到開店。</h2><ol class="opening">'+''.join(f'<li><span>0{i}</span><div><h3>{a}</h3><p>{b}</p></div></li>' for i,(a,b) in enumerate([('場地與區域評估','確認區域名額、商圈、現場條件。'),('格局與報價','確認動線、設備、施工範圍與費用。'),('系統與設備建置','建立門市、方案、付款與控電設定。'),('測試、交接與開店','走過顧客流程，完成操作與日常 SOP 交接。')],1))+'</ol>')+section('<h2>合作前，先說清楚。</h2>'+faq(franchisefaq))+section('<div class="closing"><h2>先聊地點，<br>再一起算清楚。</h2><div>'+link(LINE,'LINE 洽詢加盟','button')+link('tel:0809099006','免付費 0809-099-006','text-link')+'</div></div>','closing-section'))
P['/franchise/system/']=('ONE 營運系統｜APP、後台與智慧設備','從顧客預約、付款、訂單到控電、自助繳費與店家後台，查看 ONE 真實產品畫面。',intro('顧客用得順，<br>店家看得清。','ONE APP × 店家後台 × 現場設備')+section(system())+section(appstory(),'soft')+section(addons)+section('<div class="closing"><h2>了解系統，<br>再看開店方案。</h2>'+link('/franchise/#pricing','看 30 萬方案與收費','button')+'</div>'))
P['/about/']=('品牌故事｜ONE桌遊','ONE桌遊從 2023 年第一間店開始，打造更自由、更方便的自助休閒體驗。',intro('想聚在一起，<br>就有一個地方。','這是 ONE 開始的原因。')+section('<div class="split story-about"><div><span class="big-year">2023</span><h2>從第一間店開始。</h2><p>朋友想聚在一起，不應該受限於櫃台與繁瑣流程。我們開始把預約、付款、自助設備與門店系統接在一起。</p><p>系統進到現場，才知道什麼需要調整。ONE 一邊經營，一邊改善，從一間店走到超過百間品牌門市。</p><p>科技留在背後，讓大家把時間留給相聚。</p></div>'+photo('one-yizhong-entrance','台中一中店・入口實景')+'</div>')+proof()+finalcta())
P['/contact/']=('聯絡 ONE｜客服與加盟洽詢','ONE桌遊消費客服、品牌加盟與合作聯絡入口。',intro('你需要哪一種協助？','消費問題找客服，開店規劃找加盟團隊。')+section('<div class="contact-lines"><article><h2>預約與門市客服</h2><p>訂單、續時、付款或現場設備問題。</p>'+link(LINE,'LINE 官方客服 @oneju','button')+link('tel:0970199296','0970-199296')+'</article><article><h2>加盟與開店規劃</h2><p>提供預計地區、場地狀況與開店時間，一起討論。</p>'+link(LINE,'LINE 加盟洽詢','button')+link('tel:0809099006','免付費 0809-099-006')+'</article></div>')+section('<p>品牌營運：遊戲家資訊科技有限公司 · 統一編號 95468883<br>台中市西屯區中清路三段225巷12弄9號</p>'))
P['/privacy/']=('隱私與網站使用說明｜ONE桌遊','ONE 官網的門市查詢、定位及外部預約服務說明。',intro('隱私與網站使用說明','更新日期：2026 年 10 月 7 日')+section('<div class="legal"><h2>官網與預約服務</h2><p>本網站提供品牌介紹、門市查詢與合作資訊。預約、登入、付款等操作會前往 ONE 預約系統或 LINE 等外部服務，適用該服務公布的條款與隱私政策。</p><h2>附近門市與定位</h2><p>只有點選「找附近門市」後，網站才向瀏覽器請求定位。座標僅在本機計算門市距離，不送至本官網伺服器。你可拒絕或在瀏覽器取消授權，仍能使用縣市與文字搜尋。</p><h2>圖片及第三方服務</h2><p>門市圖片可能由 ONE 既有圖片服務載入；開啟外部預約、地圖或 LINE 連結時，外部服務會依其政策處理連線與使用資料。</p><h2>費率與可用情況</h2><p>門市名錄為更新日期的公開資料，空位、營業狀態與消費費用以預約頁和門市最新公告為準。加盟報價以正式合作文件列明範圍為準，不構成收益保證。</p><h2>聯絡</h2><p>資料或隱私相關問題可透過官方 LINE @oneju 或 0809-099-006 聯絡遊戲家資訊科技有限公司。</p></div>'))
header='<a class="skip" href="#main">跳至主要內容</a><header><div class="nav-wrap"><a href="/" class="brand" aria-label="ONE桌遊首頁"><img src="/one-logo.jpg" alt="" width="46" height="46"><span>ONE桌遊</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="main-nav">選單</button><nav id="main-nav" aria-label="主要導覽">'+''.join(link(u,t,'nav-link') for u,t in nav)+link('/support/','客服','nav-link')+link(BOOK,'立即預約','button')+'</nav></div></header>'
footer='<footer><div class="wrap"><div class="footer-top"><div><a class="brand" href="/"><img src="/one-logo.jpg" alt="" width="46" height="46"><span>ONE桌遊</span></a><p>想玩，就來。</p><small>A brand by GAMEHOME／遊戲家資訊科技</small></div><div class="footer-links">'+''.join(link(u,t) for u,t in nav)+link('/contact/','聯絡我們')+link('/privacy/','隱私與網站說明')+'</div></div><div class="footer-bottom"><span>© 2026 ONE桌遊</span><span>門市營業時間、設備與服務以各店公告為準。</span></div></div></footer><nav class="mobile-actions" aria-label="快速操作">'+link('/find/','找門市')+link(BOOK,'立即預約')+link('/support/','客服')+'</nav><dialog id="image-dialog" aria-labelledby="image-title"><div class="dialog-head"><h2 id="image-title"></h2><button data-close>關閉 ×</button></div><img alt=""></dialog>'
for route,(title,desc,body) in P.items():
 out=R/route.strip('/')/'index.html';out.parent.mkdir(parents=True,exist_ok=True)
 schema={'@context':'https://schema.org','@type':'Organization','name':'ONE桌遊','url':'https://home.onegame.tw/','logo':'https://home.onegame.tw/one-logo.jpg'}
 out.write_text(f'<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(title)}</title><meta name="description" content="{e(desc)}"><meta name="theme-color" content="#faf8f2"><link rel="canonical" href="https://home.onegame.tw{route}"><meta property="og:title" content="{e(title)}"><meta property="og:description" content="{e(desc)}"><meta property="og:image" content="https://home.onegame.tw/images/one-yadong-sage.jpg"><link rel="icon" href="/one-logo.jpg"><link rel="stylesheet" href="/assets/one.css?v=20261007"><script src="/assets/one.js?v=20261007" defer></script><script type="application/ld+json">{json.dumps(schema,ensure_ascii=False)}</script></head><body>{header}<main id="main">{body}</main>{footer}</body></html>')
# Preserve incoming historical URLs, remove their obsolete commercial promises from public pages.
for old,target in [('brand-story.html','/about/'),('franchise-light/index.html','/franchise/'),('franchise-pro/index.html','/franchise/'),('site-selection-guide.html','/franchise/#territory'),('index-dark-backup.html','/'),('index-v1.0.html','/')]:
 (R/old).write_text(f'<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="robots" content="noindex"><meta http-equiv="refresh" content="0;url={target}"><link rel="canonical" href="https://home.onegame.tw{target}"><title>ONE桌遊</title></head><body><a href="{target}">前往新版 ONE桌遊官網</a></body></html>')
(R/'404.html').write_text('<!doctype html><html lang="zh-Hant"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/assets/one.css"><title>找不到頁面｜ONE桌遊</title><main class="wrap section"><h1>換個入口，繼續找。</h1><p>這個頁面可能已經更新。</p><a class="button" href="/find/">找門市</a> <a href="/">回首頁</a></main></html>')
(R/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>https://home.onegame.tw{r}</loc></url>' for r in P)+'</urlset>')
(R/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: https://home.onegame.tw/sitemap.xml\n')
print('Built',len(P),'pages and legacy redirects')
